language: android
android:
  components:
    - android-28
    - build-tools-28.0.3

env:
  global:
    - ADB_INSTALL_TIMEOUT=8

before_script:
  - chmod +x gradlew

script:
  - ./gradlew clean assembleDebug assembleRelease
